// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grvpvibtsxnyauhiopok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdydnB2aWJ0c3hueWF1aGlvcG9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4OTkzMTcsImV4cCI6MjA2NDQ3NTMxN30.gG-hqiBF_eX-UeV-mO3XSjHcn_rsyjJ_j0nc2p-1ifk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);